# Generated by Django 4.1.2 on 2023-01-12 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunes', '0005_playlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
